---
apiVersion: v1
kind: Service
metadata:
  name: astronomy-service
  labels:
    project: astronomy
    tier: backend
    app: astronomy-service
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    project: astronomy
    tier: backend
    app: astronomy-service
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    project: astronomy
    tier: backend
    app: astronomy-service
  name: astronomy-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        project: astronomy
        tier: backend
        app: astronomy-service
    spec:
      containers:
      - name: astronomy-service
        image: ${CONTAINER_REGISTRY}.azurecr.io/astronomy-server:${IMAGE_TAG}
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
      restartPolicy: Always